### ISSUE TITLE
🐛 CoP Mission 8-1 progression issue with NMs

### ISSUE THREAD

**Issue by Harfainx** [DerpyProjectGroup/topaz#6018] opened 2024-07-18 19:01 UTC
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## Branch affected by issue 

`base`

## Steps to reproduce

- Chains of Promathia mission 8-1
- Examine crystalline field for a cutscene - working
- Examine rubious crystals one by one. Only one (1) set of NMs are spawning - After first NMs, always says "There is nothing of interest here."

- Myself and several others have only gotten 1 single NM trio to spawn. The cutscene plays after checking the crystal again. Unable to spawn second or third set of NMs. This has been verified by multiple people over multiple days, without any other players in the zone.

## Expected behavior 

- Examine rubious crystal.
- NM trio spawns
- Check crystal again for cutscene
- Repeat for other 2 crystals

**Comment by RAIST5150** [comment] 2024-07-18 19:37
UmeboshiXI may be able to provide some insight on this... #5966 was closed without further discussion/details on what was seen last month when they were having issues with this mission.

**Comment by UmeboshiXI** [comment] 2024-07-22 18:24
I assumed it was caused by something I did wrong (We had some issues on our server when the BCNMs were being converted) that caused the players' mission bits to get messed up.

 I ended up "fixing" it by rebuilding each character's mission data (Wiping out the mission blob and then adding/completing all the missions the player had.)
 
 But if you're also having issues, maybe there is more to it.

**Comment by Scarface-x** [comment] 2024-08-21 04:35
I can confirm this issue, exactly the same as [Harfainx](https://github.com/Harfainx) described. 

Any update on this?

**Comment by Xaver-DaRed** [comment] 2024-08-27 18:28
This should be fixed by PR #6175

**Closed as completed by Xaver-DaRed** 2024-08-27 18:28 UTC
Labels: bug
