### ISSUE TITLE
🐛 ROZ mission 8 Return to Delkfutt's Tower

### ISSUE THREAD

**Issue by GravesXI** [DerpyProjectGroup/topaz#2472] opened 2022-08-06 22:21 UTC
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce

When doing ROZ mission 8 Return to Delkfutt's Tower you can do the fight but when exiting the fight instead of cs you just get a black screen where you can target yourself and others but the cs will never start and it wont let you finish the mission

**Comment by RAIST5150** [comment] 2022-08-07 02:04
Just to rule it out... make sure addons/plugins that do things like tweak frame rate, auto advance dialogues, etc. are not active.   They have been known to cause issues with cut scenes in the past.

**Comment by GravesXI** [comment] 2022-08-07 06:05
We have had over 15 people with the issue over the past 3 days I even tested without add ons and had the same issue

**Comment by WinterSolstice8** [comment] 2022-08-07 07:07
Could not reproduce on new char:

Steps taken:

- `!addmission 3 16`
- `!pos 122.452 -9.009 -12.052 252`, talk to gilgamesh
- `!pos 20 3 -58 245`, talk to Aldo
- `!zone 184` and wait for CS to finish
- `!pos -520 -4 17 179` and enter BC with Qe'lov gate
- `!hp 0` on boss, here I had to wait for CS and I was _not_ ejected from the battlefield area until after. 
Does this differ for you?

**Comment by GravesXI** [comment] 2022-08-07 13:27
When the boss dies people was not getting a cs was only getting a black screen and was never ejected and was without add-ons

**Comment by Mortalelite** [comment] 2022-08-07 15:00
Just a long shot but wonder if anyone doing 60FPS, I have known in the past that can cause black screen with some CS

**Comment by claywar** [comment] 2022-08-07 15:17
Can you also ensure that the players involved are using the latest and unmodified retail clients?

**Comment by GravesXI** [comment] 2022-08-07 21:43
i tried again on a fresh build no addons no plugins fps 29 and still getting black screen after the fight and not getting cs

**Comment by HaxPrime** [comment] 2022-08-07 21:47
Reporting the same error on a base LSB server, updated just now. Client is current. No addons or plugins.
Upon defeating Kam'lanaut the end of mission cut scene does not start, it's a black screen and the player can not progress
![ffxi_2022 08 07_16 39 31](https://user-images.githubusercontent.com/108164867/183312150-18b193d3-f71f-4562-a438-77a1c9978d1f.jpg)
.

**Comment by claywar** [comment] 2022-08-07 21:57
Can you please attempt to reproduce this with an unmodified client?  The above screenshot indicates dat mods.

**Comment by HaxPrime** [comment] 2022-08-07 22:29
> Can you please attempt to reproduce this with an unmodified client? The above screenshot indicates dat mods.

Good catch I often forget XI view is not in xi pivot. Updated client just now, same results
![ffxi_2022 08 07_17 26 30](https://user-images.githubusercontent.com/108164867/183313471-eb99affb-fd16-44e4-9c4b-cfcf5161874e.jpg)
.

**Comment by N3ckB3ard** [comment] 2022-08-07 23:00
The only way I was able to get this CS is testing on retail and returning it with a GM command

!cs 17 179
![image](https://user-images.githubusercontent.com/98081508/183314345-6cff6686-4a79-4fdb-9916-087ae0c2c3f6.png)

**Comment by claywar** [comment] 2022-08-08 00:19
I should have seen this above all, but the visibility of the compass meant that the next CS didn't get fired after 32001.  This isn't a freeze (as I think most of us suspected), but rather a logic error.  Fixed in #2476

**Comment by GravesXI** [comment] 2022-08-08 06:39
Thank you for fixing

**Closed as completed** 2022-08-08 06:39 UTC
Labels: bug

**Comment by Gradius2** [comment] 2022-08-28 02:13
Well, I'm doing Zilart again.

After CS with the "floating guy", and BEFORE enter BC and killing him, it just won't let me enter.

I'm at Qe'lov Gate I click and nothing happens.  I tried on my 2nd account and I'm getting the very same problem.

I even did !delmission 3 16, logout, restarted everything (client+server), logged in, typed !addmission 3 16, did all again, and 100% same problem.

So, isn't fixed.

**Comment by TeoTwawki** [comment] 2022-08-28 04:00
> I even did !delmission 3 16, logout, restarted everything (client+server), logged in, typed !addmission 3 16, did all again, and 100% same problem.

but did you wipe the variable? the mission commands don't clear the variables used, the variable is likely why it won't "go". When code changes happen there is no way to automate updating variable on players that were mid mission prior to the update (its just not possible). I'm not saying there can't be something else wrong, but it's pretty common to have variable problems like I am describing in situations like this so its worth checking.

**Comment by GravesXI** [comment] 2022-08-28 07:19
If you !checkvar you should show up as 2 with all the changes to the mission and the stellar fulcrum the bcnm.lua was looked over so you will never enter because the var in the bcnm.lua was never changed to 2 i submitted a fix so if it gets approved you wouldn't have any issues after

**Comment by TeoTwawki** [comment] 2022-08-28 16:22
> If you !checkvar you should show up as 2 with all the changes to the mission and the stellar fulcrum the bcnm.lua was looked over so you will never enter because the var in the bcnm.lua was never changed to 2 i submitted a fix so if it gets approved you wouldn't have any issues after

gotcha, thx for the pr.

**Comment by Gradius2** [comment] 2022-08-29 06:00
I see.  Thanks for that command.
