### ISSUE TITLE
The Black Coffin fight not working properly

### ISSUE THREAD

**Issue by dfurda18** [DerpyProjectGroup/topaz#4890] opened 2023-12-21 17:07 UTC
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)

 Windows10

## Branch affected by issue

`base`

## Steps to reproduce

1. Go into `The Black Coffin` mission battle.
2. Kill the first 5 enemies.
3. The second wave of enemies take around 15-20 seconds to appear.
4. They all start attacking immediately.
5. There battle messages: `ID.text.OVERPOWERED_CREW` and `ID.text.TEST_YOUR_BLADES` should appear
6. The mob `Ashu Talif Captain` doesn't show, or appear as it does in retail (jump animation).
7. The mob `Ashu Talif Captain` cannot be targeted manually and/or attacked.
8. The mob `Ashu Talif Captain`cannot be damaged with AoE effects (tested with `Full Cleave`.

## Expected behavior
1. Go into `The Black Coffin` mission battle.
2. Kill the first 5 enemies.
3. The second wave of enemies should appear immediately.
4. The corresponding battle messages should appear.
5. The mob `Ashu Talif Captain`should appear in the middle with the jump animation.
6. The mob `Ashu Talif Captain` should be targeted and damaged to complete the mission.

**Comment by TeoTwawki** [comment] 2023-12-21 17:43
Linking topic and issue: #4889

**Comment by RAIST5150** [comment] 2023-12-21 18:19
...growling noises...
#4790 
#1976

**Comment by TeoTwawki** [comment] 2023-12-21 18:53
> ...growling noises... 

> #4790 

Keeping the newer issue, as reproduction steps are more detailed and taking the captain to 0 was the wrong requirement anyway (he gives up at 20% according to his code comments).

> #1976

_frustrated caveman grunts_ "[Aeisu](https://github.com/Aeisu) closed this as [completed](https://github.com/LandSandBoat/server/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3Acompleted) [on Jul 22, 2022](https://github.com/LandSandBoat/server/issues/1976#event-7046728558)"

**Comment by TeoTwawki** [comment] 2023-12-21 19:34
small update: confirmed its not a shift issue. the new mobs got added after the old ones for a change. And going back in the commit history, this looks like it was broken for many years and several servers modified their own forks to get around it.

**Comment by cocosolos** [comment] 2023-12-21 22:54
Couple issues here. [Ashu Talif Captain is set to link.](https://github.com/LandSandBoat/server/blob/a7df8892c12354c853eeaf21498f116f720771bc/sql/mob_pools.sql#L318) If you set him to not link, he will still link because he is also flagged `MOBTYPE_BATTLEFIELD`. [This makes him link regardless of his link setting.](https://github.com/LandSandBoat/server/blob/a7df8892c12354c853eeaf21498f116f720771bc/src/map/zone_entities.cpp#L236C31-L236C31) If you set his `link` field to 0 and `mobType` to 2 you can attack him like normal, but he'll be missing whatever battlefield-specific tweaks we apply [here.](https://github.com/LandSandBoat/server/blob/a7df8892c12354c853eeaf21498f116f720771bc/src/map/utils/mobutils.cpp#L1042)

**Comment by cocosolos** [comment] 2023-12-21 22:55
And I guess I should add that because he links, he immediately enters combat without roaming, so his roam script doesn't execute.

**Comment by TeoTwawki** [comment] 2023-12-21 23:08
> he will still link because he is also flagged MOBTYPE_BATTLEFIELD

small note: before change I made earlier code involved would have been checking for zonetype battlefield instead of mobtype. Which may have only acted on BCNM style fights and not instance style battles I'm note sure. But the issue predates this change as the 1st issue in our tracker about it is over a yr old. The issue probably dates all the way back to when someone decided to auto-link everything in the same fight automatically but I stopped digging before getting that far.

(I killed the zonetype for this entirely)

I this is still unfixed when I get my time off in january I'll see if I can get'r'done.

**Comment by TeoTwawki** [comment] 2023-12-21 23:12
we could possibly work around it by manually deleting his superlink modifier and forcing him to not agro (there is another modifier for that) until phase 2 of the fight starts.

**Comment by cocosolos** [comment] 2023-12-21 23:27
Superlink mobmod is actually being set to 0 for instance mobs which resolves to false, so it's just the `link` and `mobType`.

**Comment by TeoTwawki** [comment] 2023-12-22 00:31
in the function you linked to mobType appears to only be affecting the linking via superlink mobmod, so maybe its as simple as setting him to non linking in his pool after all if that doesn't happen on instances

**Comment by TeoTwawki** [comment] 2023-12-22 00:33
bah FindPartyForMob affects instances doesn't it?

<sulking>

**Comment by cocosolos** [comment] 2023-12-22 00:33
> bah FindPartyForMob affects instances doesn't it?

Yep.
```cpp
if ((forceLink || PMob->m_Link || PMob->m_Type & MOBTYPE_BATTLEFIELD) && PMob->PParty == nullptr)
```

**Comment by cocosolos** [comment] 2023-12-22 00:36
Tying linking and mob parties and battlefields together is convenient in the general case, but is a pain for special cases. Ran into similar issues in Limbus as well.

**Comment by TeoTwawki** [comment] 2023-12-22 00:36
ya know. I would really rather we not always assume everything should always link. Its very inflexible. Especially when we already have (multiple) controls to make it happen or not that this gets in the way of. I get that we don't want to have to manually set each and every one of them but as we can see, this is just as much a pain in the rear end.

**Comment by TeoTwawki** [comment] 2023-12-22 00:36
Jinx?

**Comment by TeoTwawki** [comment] 2023-12-22 00:39
maybe the answer is just a flagging the bcnm mobs with a yes or no for this behavior in the rows for bcnm and instances in their respective tables. bcnm has a conditions column we coudl add to, instances do not (yet).

**Comment by GravesXI** [comment] 2024-01-12 09:56
I just did the fight I found I couldn't attack the captain after the 3rd time trying the fight I let him kill Gessho then he would jump in normally and could fight him and kill him then if that helps any

**Comment by TeoTwawki** [comment] 2024-01-12 17:42
> I just did the fight I found I couldn't attack the captain after the 3rd time trying the fight I let him kill Gessho then he would jump in normally and could fight him and kill him then if that helps any

because after he killed Gessho he went idle momentarily, allowing his logic to finally fire off.

**Closed as completed** 2024-01-12 20:56 UTC
Labels: bug

**Comment by TeoTwawki** [comment] 2024-01-12 20:58
while the recent PR should not make the battlefield passable, the issue of automatic engage is still on the radar so to speak. this won't be the only time its a problem for sure.
