### ISSUE TITLE
Build error on raspberry pi os 32 bit

### ISSUE THREAD

**Issue by sethbayens** [DerpyProjectGroup/topaz#3619] opened 2023-02-19 14:24 UTC
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)

 raspberry pi os 32 bit

## Branch affected by issue 

`base`

## Expected behavior

[ 29%] Built target xi_search
/usr/bin/ld: /tmp/xi_world.2dkwgt.ltrans7.ltrans.o: in function `HTTPServer::LockingUpdate()':
/usr/include/c++/10/atomic:258: undefined reference to `__atomic_load_8'
/usr/bin/ld: /usr/include/c++/10/atomic:247: undefined reference to `__atomic_store_8'
collect2: error: ld returned 1 exit status
make[2]: *** [src/world/CMakeFiles/xi_world.dir/build.make:508: ../xi_world] Error 1
make[1]: *** [CMakeFiles/Makefile2:1082: src/world/CMakeFiles/xi_world.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

**Comment by zach2good** [comment] 2023-02-19 19:58
Duplicate of https://github.com/LandSandBoat/server/issues/3618

**Closed as completed by zach2good** 2023-02-19 19:58 UTC
Labels: bug
