### ISSUE TITLE
!!! CRASH !!!

### ISSUE THREAD

**Issue by cejiasa** [DerpyProjectGroup/topaz#1393] opened 2022-03-09 14:24 UTC
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: EDITME

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

[03/09/22 09:11:56:470][critical][stacktrace] ================================================================
[03/09/22 09:11:56:470][critical][stacktrace] !!! CRASH !!!
[03/09/22 09:11:56:470][critical][stacktrace] Exception STATUS_HEAP_CORRUPTION (0XC0000374) occured!
[03/09/22 09:11:56:470][critical][stacktrace] ================================================================
[03/09/22 09:11:56:470][critical][stacktrace] Process Name: topaz_game_64.exe
[03/09/22 09:11:56:470][critical][stacktrace] Process Uptime: 72 minutes
[03/09/22 09:11:56:470][critical][stacktrace] Process Memory Usage 1354MiB / 32768MiB
[03/09/22 09:11:56:470][critical][stacktrace] Git SHA: baa0d7865fa08699bca7c29a896301950b8e638b-dirty
[03/09/22 09:11:56:470][critical][stacktrace] Git Date: Mon Jan 31 07:42:13 2022
[03/09/22 09:11:56:470][critical][stacktrace] Git Branch: base
[03/09/22 09:11:56:470][critical][stacktrace] Git Subject: Merge pull request #1225 from TeoTwawki/base
[03/09/22 09:11:56:470][critical][stacktrace] ================================================================
[03/09/22 09:11:56:556][critical][stacktrace] at RtlIsZeroMemory, address 0x7FFD77B4F080.
[03/09/22 09:11:56:556][critical][stacktrace] in C:\WINDOWS\SYSTEM32\ntdll.dll
[03/09/22 09:11:56:556][critical][stacktrace] at RtlIsZeroMemory, address 0x7FFD77B4F080.
[03/09/22 09:11:56:556][critical][stacktrace] in C:\WINDOWS\SYSTEM32\ntdll.dll
[03/09/22 09:11:56:556][critical][stacktrace] at RtlpNtSetValueKey, address 0x7FFD77B57A30.
[03/09/22 09:11:56:556][critical][stacktrace] in C:\WINDOWS\SYSTEM32\ntdll.dll
[03/09/22 09:11:56:556][critical][stacktrace] at RtlpNtSetValueKey, address 0x7FFD77B57A30.
[03/09/22 09:11:56:556][critical][stacktrace] in C:\WINDOWS\SYSTEM32\ntdll.dll
[03/09/22 09:11:56:556][critical][stacktrace] at RtlpNtSetValueKey, address 0x7FFD77B57A30.
[03/09/22 09:11:56:556][critical][stacktrace] in C:\WINDOWS\SYSTEM32\ntdll.dll
[03/09/22 09:11:56:556][critical][stacktrace] at memset, address 0x7FFD77AF3E00.
[03/09/22 09:11:56:556][critical][stacktrace] in C:\WINDOWS\SYSTEM32\ntdll.dll
[03/09/22 09:11:56:556][critical][stacktrace] at RtlFreeHeap, address 0x7FFD77A74760.
[03/09/22 09:11:56:556][critical][stacktrace] in C:\WINDOWS\SYSTEM32\ntdll.dll
[03/09/22 09:11:56:556][critical][stacktrace] at free_base, address 0x7FFD757DF040.
[03/09/22 09:11:56:556][critical][stacktrace] in C:\WINDOWS\System32\ucrtbase.dll
[03/09/22 09:11:56:569][critical][stacktrace] at CBasicPacket::`scalar deleting destructor', address 0x7FF72BA1A9B0.
[03/09/22 09:11:56:569][critical][stacktrace] in D:\server\topaz_game_64.exe
[03/09/22 09:11:56:569][critical][stacktrace] at CCharEntity::erasePackets in D:\server\src\map\entities\charentity.cpp: line: 351: address: 0x7FF72BAD8630
[03/09/22 09:11:56:569][critical][stacktrace] at send_parse in D:\server\src\map\map.cpp: line: 784: address: 0x7FF72BA21AB0
[03/09/22 09:11:56:570][critical][stacktrace] at do_sockets in D:\server\src\map\map.cpp: line: 418: address: 0x7FF72BA1F880
[03/09/22 09:11:56:570][critical][stacktrace] at main in D:\server\src\common\kernel.cpp: line: 268: address: 0x7FF72BAAFE30

**Comment by zach2good** [comment] 2022-03-09 14:28
Likely duplicate of https://github.com/LandSandBoat/server/issues/1375

**Comment by zach2good** [comment] 2022-10-16 13:46
I haven't seen or heard of any instances of this error in the past 6 months, so I'm going to close this issue. If this is still a problem feel free to re-open it.

**Closed as completed by zach2good** 2022-10-16 13:46 UTC
