### ISSUE TITLE
[Limbus: NE Apollyon] Bugs / Wrong Stuff

### ISSUE THREAD

**Issue by ShiyoKozuki** [DerpyProjectGroup/topaz#879] opened 2021-10-26 18:27 UTC
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: EDITME

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
Courtesy of Delius(Delius#2340)

NE Apollyon
Floor 1
 - TEs are giving 15 minutes instead of 5 minutes
 - Goobbue Harvester missing enparalyze
 - Mandragoras need to be given alliance hate

Floor 2
 - TEs are giving 15 minutes instead of 5 minutes
 - Bialozar currently link with the birds at their side, they should not
 - Thiazi currently link with the birds at their side, they should not
 - Rocs sleepable, should be immune
 - Rocs shouldn't self buff, they should only horde lullaby and massacre elegy
 - Too many chests are spawning on this floor? Something is off here possibly fake chests, the birds are spawning chests after death which im not sure is accurate.
In one run I got 6 blue chest 3 of those did not extend time and 4 gold chests 3 of which did not reward items
 - Thiazi and Bialozar should aggro True Sound (Siknoz tested on retail they aggroed with sneak on when he got within sound aggro range)
 - Sirins have too much hp (8500) should be 4000 according to Siknoz's capture

Floor 3
 - TEs are giving 15 minutes instead of 5 minutes
 - A small pot dropped the item chest, it should come from the large pot only
 - Pots should True sight aggro
 - Pots should not link with the doll

Floor 4
 - TEs are giving 15 minutes instead of 5 minutes
 - Gigas placement is static, seems to be random according to video footage
 - Kerkopes Spinning Claw too weak, currently doing ~200 damage. According to wiki "Spinning Claw can do over 1000 damage to everyone in the 15' range."
 - Cronos is Immune to Physical ranged attack, should only be melee and physical blu spells
Floor 5
 - Light based sleeps are landing on Troglodyte Dhalmels too easily, should be either very resistant or immune according to wiki
 - Criosphinx and Hieracosphinx:
 - Not immune to Slow or Elegy, landed both with ease 1/1
 - Should be "Highly Resistant, if not immune to Gravity, Bind, and Sleep" landed all with ease 1/1
 - Can sneak/invisible past Hieracosphinx, Needs to be True Sight and True Sound
 - Can sneak past Criosphinx, Needs to be True Sight and True Sound
 - Both need double attack trait
 - When Siknoz killed Hieracosphinx in his retail capture, Criosphinx had a 2hr animation activate with no message in the log of what it was. When this happened it seemed to have 100% double attack

**Comment by cocosolos** [comment] 2022-02-06 01:32
> - Mandragoras need to be given alliance hate
> - Bialozar currently link with the birds at their side, they should not
> - Thiazi currently link with the birds at their side, they should not
> - Pots should not link with the doll

I believe these are caused by [this block](https://github.com/LandSandBoat/server/blob/67f34fc7eb251d5f006d5210ff302099ab94c78e/src/map/utils/mobutils.cpp#L556) being executed instead of the Limbus block below it. I think most or all Limbus mobs are marked as MOBTYPE_BATTLEFIELD (18) in mob_pools.sql. This will prevent alliance hate from being set, normal roaming on some floors of some battlefields, possibly mobs returning home (#896), and will add superlinking to all mobs. I'm not sure if any of these pools are being used for other battlefields, but if not it should be safe to set them to MOBTYPE_NORMAL (0). Alternatively the battlefield check in mobutils could probably be moved below the Limbus check.

**Closed as completed** 2022-10-27 03:23 UTC
