### ISSUE TITLE
Crash during call to mysql_ping

### ISSUE THREAD

**Issue by cejiasa** [DerpyProjectGroup/topaz#1286] opened 2022-02-13 23:11 UTC
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: EDITME

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
[Crash.txt](https://github.com/LandSandBoat/server/files/8056888/Crash.txt)

This crash happens at random times through the day same error each time no real reason that i have found out. There was a similar issue in one of the past post but, there seem to be no real fix to it or i didn't understand what the fix was. This error has been stumping me for months, any help would be appreciated. thank you

**Comment by ghost** [comment] 2022-02-14 01:23
Possible Related Old Issues
[#625](https://github.com/LandSandBoat/server/issues/625)

**Comment by CatsEyeXI** [comment] 2022-02-14 02:39
I will also jump on board with this one... It's currently the only crash we're experiencing... we're running

Windows 10 Pro
MariaDB 10.6

topaz_*.exe and mariadb are running on the same box... Connecting over loopback address 127.0.0.1
No other interruption in network connectivity appears to correlate to this.

**Comment by CatsEyeXI** [comment] 2022-02-16 21:23
Hello, I've experienced one of this crashes since zach merged PR #1288 

![image](https://user-images.githubusercontent.com/65316697/154359380-bed57bc5-c287-4c7c-bad8-f8c87c501853.png)

let me know if you need more info

**Comment by zach2good** [comment] 2022-02-17 06:31
@beneliezer did you let this run far enough for the `std::runtime_error` part to log out what it caught? That's the thing we're trying to catch

https://en.cppreference.com/w/cpp/language/function-try-block

I suspect it'll just say `Exception STATUS_ACCESS_VIOLATION (0XC0000005) occured!`, but we don't have much else to go on at the moment 🤷

**Comment by zach2good** [comment] 2022-02-17 07:28
I made a small test project to test out how `mysql_ping` operates, and I can't get it to crash 😕 
```cpp
    spdlog::info("Trying mysql_init, ping, and close");
    try
    {
        MYSQL* mysql = mysql_init(NULL);
        std::cout << "mysql_real_connect " << mysql_real_connect(mysql, "localhost", "root", "root", "xidb", 3306, nullptr, 0) << "\n";
        for (size_t i = 0; i < 100; i++)
        {
            auto rc = mysql_ping(mysql);
            std::cout << "mysql_ping " << rc << "\n";
            if (rc == 1)
            {
                std::cout << "mysql_real_connect " << mysql_real_connect(mysql, "localhost", "root", "root", "xidb", 3306, nullptr, 0) << "\n";
            }
            else
            {
                std::this_thread::sleep_for(std::chrono::seconds(1));
            }
        }
        mysql_close(mysql);
    }
    catch(const std::exception& e)
    {
        std::cerr << "ERROR!:" << e.what() << '\n';
    }
```

```
[2022-02-17 09:25:22.520] [info] Trying mysql_init, ping, and close
mysql_real_connect 0000021D65B0B8B0
mysql_ping 0
mysql_ping 0
mysql_ping 0
mysql_ping 0
mysql_ping 0
(switch MariaDB service off)
mysql_ping 1
(blocks until I turn MariaDB service back on)
mysql_real_connect 0000021D65B0B8B0
mysql_ping 0
mysql_ping 0
mysql_ping 0
mysql_ping 0
mysql_ping 0
mysql_ping 0
mysql_ping 0
mysql_ping 0
mysql_ping 0
mysql_ping 0
```

**Comment by cejiasa** [comment] 2022-02-17 11:55
> * [x]  I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
> 
>     * [x]  I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
> 
>     * [x]  I have checked the commit log to see if the issue has been resolved since my server was last updated
> 
>     * [x]  I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
> 
>     * [x]  I have specified what branch this happens on branch: EDITME
> 
> 
> **_Additional Information_** (Steps to reproduce/Expected behavior) **:** [Crash.txt](https://github.com/LandSandBoat/server/files/8056888/Crash.txt)
> 
> This crash happens at random times through the day same error each time no real reason that i have found out. There was a similar issue in one of the past post but, there seem to be no real fix to it or i didn't understand what the fix was. This error has been stumping me for months, any help would be appreciated. thank you

#

**Comment by cejiasa** [comment] 2022-02-17 12:03
didnt mean to close it hit wrong button to early in the morning. But just wanted to give you the specs of my Computer and the versions of software im running to see if it will help with the SQL ping crash problem.
 
Windows 10 Pro 64 bit version
MariaBD 10 64bit version
Python 3.10 64 bit
Visual Studio 2019 64 bit version

**Comment by RAIST5150** [comment] 2022-02-17 16:48
Can't shake the thought of some weird driver/firmware issue in play.  Like if it is happening mostly with one family of network chipsets... or even Intel versus Broadcom or something weird like that.

**Comment by CatsEyeXI** [comment] 2022-02-20 23:56
> @beneliezer did you let this run far enough for the `std::runtime_error` part to log out what it caught? That's the thing we're trying to catch
> 
> https://en.cppreference.com/w/cpp/language/function-try-block
> 
> I suspect it'll just say `Exception STATUS_ACCESS_VIOLATION (0XC0000005) occured!`, but we don't have much else to go on at the moment 🤷

Please forgive me, Zach, but how do I determine if I've let this run far enough? The data is from the automatic dumps. Should I be running the server in the interactive debugger?

**Comment by CatsEyeXI** [comment] 2022-02-22 04:28
> Can't shake the thought of some weird driver/firmware issue in play. Like if it is happening mostly with one family of network chipsets... or even Intel versus Broadcom or something weird like that.

i can confirm this is not the case, migrated my server from bare metal to VM and it still does it. Old box had Broadcom chip, new box has Intel chip.

**Comment by zach2good** [comment] 2022-02-25 13:35
I've still not had time to sit down and work out what's up with my MariaDB update PR: https://github.com/LandSandBoat/server/pull/1291

In the meantime, I've quickly thrown together a patch that will forcefully build the MariaDB client from source.
This will either:
- Stop the crash, wherever it was coming from 🤷 
- Allow us to see _where_ the crash is inside the MariaDB code, which might guide us in fixing the issue

**Diff:**
https://github.com/LandSandBoat/server/compare/experiment/build_mariadb_from_source

**As a patch:**
https://github.com/LandSandBoat/server/compare/experiment/build_mariadb_from_source.patch

**How to apply patches:**
https://gist.github.com/nepsilon/22bc62a23f785716705c

**Oneliner for Git Bash (or similar):**
`curl https://github.com/LandSandBoat/server/compare/experiment/build_mariadb_from_source.diff | git apply`

_This patch isn't intended to be used forever, only until I fix the DLL-hell I have going on in my other PR._

**Comment by cejiasa** [comment] 2022-02-27 00:22
SQL crash only happened 1 time after applying the patch here the error.

[02/26/22 19:12:27:700][map][info][info] Pinging SQL server to keep connection alive... (Sql_P_KeepaliveTimer:193)
[02/26/22 19:12:27:701][critical][stacktrace] ================================================================
[02/26/22 19:12:27:701][critical][stacktrace] !!! CRASH !!!
[02/26/22 19:12:27:701][critical][stacktrace] Exception STATUS_ACCESS_VIOLATION (0XC0000005) occured!
[02/26/22 19:12:27:701][critical][stacktrace] ================================================================
[02/26/22 19:12:27:701][critical][stacktrace] Process Name: topaz_game_64.exe
[02/26/22 19:12:27:701][critical][stacktrace] Process Uptime: 24 hours
[02/26/22 19:12:27:701][critical][stacktrace] Process Memory Usage 2336MiB / 32768MiB
[02/26/22 19:12:27:701][critical][stacktrace] Git SHA: baa0d7865fa08699bca7c29a896301950b8e638b-dirty
[02/26/22 19:12:27:701][critical][stacktrace] Git Date: Mon Jan 31 07:42:13 2022
[02/26/22 19:12:27:701][critical][stacktrace] Git Branch: base
[02/26/22 19:12:27:701][critical][stacktrace] Git Subject: Merge pull request #1225 from TeoTwawki/base
[02/26/22 19:12:27:701][critical][stacktrace] ================================================================
[02/26/22 19:12:28:017][critical][stacktrace] at ma_simple_command in D:\server\out\build\x64-Debug\_deps\mariadb-src\libmariadb\mariadb_lib.c: line: 452: address: 0x7FF75876C370
[02/26/22 19:12:28:018][critical][stacktrace] at mysql_ping in D:\server\out\build\x64-Debug\_deps\mariadb-src\libmariadb\mariadb_lib.c: line: 2901: address: 0x7FF75876D1B0
[02/26/22 19:12:28:023][critical][stacktrace] at Sql_Ping in D:\server\src\common\sql.cpp: line: 172: address: 0x7FF7582C0D00
[02/26/22 19:12:28:023][critical][stacktrace] at Sql_P_KeepaliveTimer in D:\server\src\common\sql.cpp: line: 197: address: 0x7FF7582C0DB0
[02/26/22 19:12:28:026][critical][stacktrace] at CTaskMgr::DoTimer in D:\server\src\common\taskmgr.cpp: line: 120: address: 0x7FF7582C6A50
[02/26/22 19:12:28:028][critical][stacktrace] at main in D:\server\src\common\kernel.cpp: line: 267: address: 0x7FF7582D18A0
[02/26/22 19:12:28:028][critical][stacktrace] ================================================================

**Comment by CatsEyeXI** [comment] 2022-02-27 02:06
I'm still going strong ...

**Comment by CatsEyeXI** [comment] 2022-02-27 02:07
About 36 hours now ... new record lol

**Comment by zach2good** [comment] 2022-02-28 11:55
Here's another question; check the logs: when there is a crash on `mysql_ping`, is it the first time the server has tried to ping to keep the db connection alive, or are there successful pings before the crash?

**Comment by CatsEyeXI** [comment] 2022-02-28 13:10
![image](https://user-images.githubusercontent.com/65316697/155988680-5bafea09-3fe6-4e09-b5c3-355ccd7414bb.png)

I did have successful pings bofore the crash...

02/26/22 17:04:13:883][map][info][info] Pinging SQL server to keep connection alive... (Sql_P_KeepaliveTimer:193)
[02/26/22 17:04:13:894][map][info][info] Pinging SQL server to keep connection alive... (Sql_P_KeepaliveTimer:193)

**Comment by zach2good** [comment] 2022-02-28 13:13
Any more apart from that? Note the suspiciously close timestamps

**Comment by CatsEyeXI** [comment] 2022-02-28 15:02
@Xaver-DaRed has the dump and full map-server.log from this morning..  i'm not sure what specifically you are looking for.

**Comment by zach2good** [comment] 2022-03-18 17:23
I think I found the cause for this, addressed in: https://github.com/LandSandBoat/server/pull/1420

It looks like one or both of our SQL handles were being trampled from another thread, since they were created on different threats, but both registered to the task manager (which lives on the main thread). I refactored everything so that all of our SQL stuff is encapsulated into a single object, which is entirely contained to whatever thread it is created on, and doesn't use the task manager for it's periodic pinging.

**Comment by CatsEyeXI** [comment] 2022-03-19 13:29
i haven't had this crash since 3/8/22, usually occurred at least once a day.

**Comment by zach2good** [comment] 2022-03-21 09:25
I'm fairly confident that my refactors have killed the root cause for this issue. Closing. (Please re-open if it comes back 💀 )

**Closed as completed by zach2good** 2022-03-21 09:25 UTC
