### ISSUE TITLE
RoV Reset to 1-2 (Resonance) from 2-7 (Ever Forward)

### ISSUE THREAD

**Issue by Dev-Roland** [DerpyProjectGroup/topaz#1891] opened 2022-06-06 19:41 UTC
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce

1. Progress to RoV 2-2 on a character that has not reached PM (CoP) 3-2
 - _This char cannot trigger the RoV 2-2 Ru'Lude Gardens Audience Chamber cutscene until CoP 3-2 is finished._
2. Progress to and **finish** PM 3-2 _(via triggering PM 3-2's Ru'Lude Gardens Audience Chamber cutscene)_
3. Run ~10 yalms away and then back to trigger RoV 2-2's audience chamber cutscene and **finish** RoV 2-2 (because the character needs to re-enter the same trigger area)
4. Zone to Port Jeuno to **finish** RoV 2-3
5. Zone to Upper Jeuno and click the Marble Bridge door to **finish** RoV 2-4
6. Zone to Upper Jeuno and obtain the boarding permit from Faursel to **finish** both RoV 2-5 and RoV 2-6
7. Zone to Northern Sandoria (E) Homepoint to trigger a PM 3-3 cutscene with Ulmia **(somewhere in step 6 or 7 RoV progress is reset to RoV 1-2)**
8. Zone out and back in to Northern Sandoria to trigger RoV 1-2 (Resonance)
NOTE: From here I was able to **re**-progress all the way to RoV 2-7, re-obtaining items (ciphers) but not getting duplicate KIs (good).

## Expected behavior

If this is a **halt RoV until this newly-triggered CoP mission finishes**, then RoV should pause rather than reset. If it is a different scenario then I am unsure of the expected behavior.

**Comment by claywar** [comment] 2022-06-06 19:43
Can you please help me out on this and use the BG Wiki mission numbers for RoV?  Trying to see what could be going on

**Comment by claywar** [comment] 2022-06-06 19:45
Nevermind, think I see the suspect.  Thank you for the detailed information!

**Comment by Dev-Roland** [comment] 2022-06-06 19:52
I did update the steps with BG-Wiki info and streamlined the info a little to eliminate noise. I still tried to keep a lot of details since there's so many steps in CoP and RoV that one could easily deviate from the precise path I took without granular steps.

**Comment by claywar** [comment] 2022-06-06 19:57
Great info.  The interaction with Faursel appears to be the cause, and something where I need to add some additional logging in the future to prevent such a thing from occurring again.  This instance should be fixed once the linked PR is merged.

**Comment by Dev-Roland** [comment] 2022-06-06 19:58
I see in https://github.com/LandSandBoat/server/pull/1892 that you note this is from Faursel's code. I can concur that my alt that already had a boarding permit, and therefore did not interact with that NPC, did got get his RoV progress reset! That goes along with your theory.

**Closed as completed** 2022-06-06 20:43 UTC
