### ISSUE TITLE
🐛 Overrides not applying correctly

### ISSUE THREAD

**Issue by CatsEyeXI** [DerpyProjectGroup/topaz#3412] opened 2022-12-20 16:41 UTC
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)

Windows 10

## Branch affected by issue 

`base`

## Steps to reproduce
Create the sample module below, none of the prints will fire.

```
-----------------------------------
-- Common Requires
-----------------------------------
require("modules/module_utils")
require("scripts/globals/npc_util")
require("scripts/globals/status")
require("scripts/globals/zone")
-----------------------------------
local ID = require("scripts/zones/Caedarva_Mire/IDs")

local m = Module:new("wild_karakul")

m:addOverride("xi.zones.Caedarva_Mire.mobs.Wild_Karakul.onMobSpawn", function(mob)
    print("WILD KARAKUL SPAWNED!")
end)

m:addOverride("xi.zones.Caedarva_Mire.mobs.Wild_Karakul.onMobFight", function(mob, target)
    print("WILD KARAKUL FIGHTING!")
end)

m:addOverride("xi.zones.Caedarva_Mire.mobs.Wild_Karakul.onMobDeath", function(mob, player, optParams)
    print("WILD KARAKUL DIED!")
end)

m:addOverride("xi.zones.Caedarva_Mire.mobs.Wild_Karakul.onMobDespawn", function(mob)
    print("WILD KARAKUL DESPAWNED!")
end)

return m
```

## Expected behavior

Prints should fire in each function

Per Zach:
`Presumably luautils::init(); // Also calls moduleutils::LoadLuaModules(); is being fired before zoneutils::LoadZoneList(); and the cache entries are getting clobbered
`

**Comment by TonzoffunCE** [comment] 2023-01-10 18:41
Hey @zach2good, do you have any pointers or direction as to where we could look in the code, so we can try to fix this issue? Any insight would be greatly appreciated.

**Comment by zach2good** [comment] 2023-01-11 12:17
The issue here is how the following functions interact, and the order in which they interact:
https://github.com/LandSandBoat/server/blob/base/src/map/utils/moduleutils.cpp#L234
https://github.com/LandSandBoat/server/blob/base/src/map/lua/luautils.cpp#L697
https://github.com/LandSandBoat/server/blob/base/src/map/utils/zoneutils.cpp#L524

I haven't looked into it yet, but the modules are loaded first, a table is created during the module load, and then the actual mob/npc table is loaded and cached on top of what was created for the module.

The fix isn't particularly simple, as you'll have to dig into each element of the mob/npc cache entry and compare whether or not there is nothing there, an empty func, something that has overrides (searching for the fenv super table), etc.

**Comment by TonzoffunCE** [comment] 2023-01-11 15:15
Thanks so much for your time and response, we appreciate it! We will look into this matter and see what we can do.

**Comment by zach2good** [comment] 2023-01-14 12:22
Posting from train 🚅 :

Depending on what time I get back home tomorrow, I might have some hours to work on this.

The test case is as follows (to avoid having to keep logging in with a char to make a zone wake up):

- remove the OnSpawn module entry from the module linked in OP
- put an onInit entry in the actual mob entry, and make sure the others are blank (apart from on Death, we're trying to make sure that populated functions and empty functions both override, and both fire correctly, so add logging to everything)
- using onServerStart, or whatever is in server.lua, make naked calls to xi.zone.Mire.mobs.mobName.onInit and OnSpawn, and hopefully see the correct logging for everything.

Implementation will have to be something like this:
- load all modules, have them ready but not applied
- for every time we create a cache entry, iterate over all the functions in it and apply each override, rather than clobbering over the top of whatever is there
- while doing this, if we get to the end of the cache object and there's overrides left to apply, that's when we should be injecting blank functions that we can then override, so do inject, and then apply overrides again
- if we go through all the mobs and overrides for zones on the current process, and still have overrides left over, we are either in a bad state, or need to insert dummy cache entries

For the future hot reloading of modules (out of scope for this pr), we need to link each global thing that's overridable to the file it originates from, so we can do a full reload and re-apply of modules. The other option is look at the cache entry and see if super is defined. If it is, then we're in an override and we should peel off the current impl and replace it with what's in super. We should keep doing this until super is nil, then we have the original impl. Then we can reapply modules.

/minddump

**Comment by zach2good** [comment] 2023-01-14 12:26
Also todo; make sure that claim_shield module and hnm modules still work as intended (might need help with hnm, I didn't write it and I never really did hnm stuff, so I don't understand all the fuss)

**Comment by zach2good** [comment] 2023-01-15 19:19
Findings so far:

```lua
Wild_Karakul.lua:
entity.onMobSpawn = function(mob)
    print("entity.onMobSpawn")
end

test.lua:
m:addOverride("xi.zones.Caedarva_Mire.mobs.Wild_Karakul.onMobSpawn", function(mob)
    super(mob)
    print("WILD KARAKUL SPAWNED!")
end)
```

I modified `applyOverride` to return `func`, so I can call it immediately from C++ and really really force the new entry into the cache:
```cpp
                        sol::function newFunc = lua["applyOverride"](table, lastElem, override.func, override.overrideName, override.filename);
                        table[sol::override_value][part] = newFunc;
                        table[part]();
```

It works as expected, with the original call and the module override being used properly.

```
[01/15/23 19:17:44:840][map][debug] Applying override: xi.zones.Caedarva_Mire.mobs.Wild_Karakul.onMobSpawn (moduleutils::TryApplyLuaModules:255)
[01/15/23 19:17:44:840][map][lua] entity.onMobSpawn (lua_print:151)
[01/15/23 19:17:44:840][map][lua] WILD KARAKUL SPAWNED! (lua_print:151)
```

But then, the actual zone calls the functions, and the overrides aren't being used:
```
[01/15/23 19:18:20:790][map][lua] entity.onMobSpawn (lua_print:151)
[01/15/23 19:18:20:790][map][lua] entity.onMobSpawn (lua_print:151)
[01/15/23 19:18:20:791][map][lua] entity.onMobSpawn (lua_print:151)
[01/15/23 19:18:20:791][map][lua] entity.onMobSpawn (lua_print:151)
[01/15/23 19:18:20:791][map][lua] entity.onMobSpawn (lua_print:151)
[01/15/23 19:18:20:791][map][lua] entity.onMobSpawn (lua_print:151)
[01/15/23 19:18:20:791][map][lua] entity.onMobSpawn (lua_print:151)
[01/15/23 19:18:20:792][map][lua] entity.onMobSpawn (lua_print:151)
[01/15/23 19:18:20:792][map][lua] entity.onMobSpawn (lua_print:151)
[01/15/23 19:18:20:794][map][lua] entity.onMobSpawn (lua_print:151)
[01/15/23 19:18:20:795][map][lua] entity.onMobSpawn (lua_print:151)
[01/15/23 19:18:20:809][map][lua] entity.onMobSpawn (lua_print:151)
[01/15/23 19:18:20:810][map][lua] entity.onMobSpawn (lua_print:151)
[01/15/23 19:18:20:810][map][lua] entity.onMobSpawn (lua_print:151)
```

So, this means one of two things: The cache entry is (lol) being cached in another place before the changes are being applied and that version is being used, or, the updated cache entry is being clobbered by an old version of the cache entry

**Comment by zach2good** [comment] 2023-01-15 19:42
Ah, I think I found it:

I put a print in the body of the Karakul script to see how many times the file was being loaded on startup: lots.

This wouldn't be such a bad thing, if I hadn't set overrides to only apply once and then bail out if something tries to apply them again.

So the file is loaded, the overrides are correctly applied, the files are loaded again, the overrides are then NOT applied.

Fix probably requires a lot of jiggling things around

**Comment by zach2good** [comment] 2023-01-15 20:26
Fixed in the linked PR ^

```
[01/15/23 20:19:13:540][map][lua] entity.onMobSpawn (lua_print:151)
[01/15/23 20:19:13:540][map][lua] WILD KARAKUL SPAWNED! (lua_print:151)
[01/15/23 20:19:13:540][map][lua] entity.onMobSpawn (lua_print:151)
[01/15/23 20:19:13:540][map][lua] WILD KARAKUL SPAWNED! (lua_print:151)
```

Removing the `entity.onMobSpawn` function:
```
[01/15/23 20:22:54:838][map][lua] WILD KARAKUL SPAWNED! (lua_print:151)
[01/15/23 20:22:54:838][map][lua] WILD KARAKUL SPAWNED! (lua_print:151)
[01/15/23 20:22:54:838][map][lua] WILD KARAKUL SPAWNED! (lua_print:151)
```

**Closed as completed** 2023-01-17 11:52 UTC
Labels: bug
