### ISSUE TITLE
🐛 conquest always a 3 nation deadlock

### ISSUE THREAD

**Issue by TeoTwawki** [DerpyProjectGroup/topaz#3800] opened 2023-04-22 04:07 UTC
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)
windows server 2019

## Branch affected by issue 
`base`

## Steps to reproduce
Conquest update messages always claim all 3 nations are in a deadlock. Its been saying this for several weeks.

Right now Windurst controls 9 areas and has a clear lead. in many zones. The conquest map does rightly show them in 1st place from the previous weeks tally, but both the regular updates and the weekend tally message seem to not realize that anybody is winning at conquest. Some of the weekend zone control shifts seem kind of fishy. I wiped out the conquest table back to default 2 weeks ago but that didn't help any, I can't tell if anything's abnormal with zone control or if its just the message.

Diagnostic suggestions to try on my next maintenance welcome, as are comments by anyone else noticing anything fishy with conquest at their server(s).

## Expected behavior
Region influenced by victory instead of tiger blood.

**Comment by RAIST5150** [comment] 2023-04-22 13:03
If it is "just" a messaging glitch (all else is behaving), could it be something up with the influence value queried here?
(section at line 1523 in conquest.lua)

```lua
xi.conquest.sendConquestTallyUpdateMessage = function(player, messageBase, owner, ranking, influence, isConquestAlliance)
    if owner <= 3 then
        player:messageText(player, messageBase + 32 + owner, 5) -- This region is currently under <nation> control.
    else
        player:messageText(player, messageBase + 31, 5) -- This region is currently under beastman control.
    end

    if influence >= 64 then
        player:messageText(player, messageBase + 37, 5) -- The beastmen are on the rise.
    elseif influence == 0 then
        player:messageText(player, messageBase + 36, 5) -- All three nations are at a deadlock.
    else
        local sandoria = bit.band(influence, 0x03)
        local bastok = bit.rshift(bit.band(influence, 0x0C), 2)
        local windurst = bit.rshift(bit.band(influence, 0x30), 4)

        player:messageText(player, messageBase + 41 - sandoria, 5) -- Regional influence: San d'Oria
        player:messageText(player, messageBase + 45 - bastok, 5)   -- Regional influence: Bastok
        player:messageText(player, messageBase + 49 - windurst, 5) -- Regional influence: Windurst
    end
```

Just can't help but wonder of GetRegionInfluence is getting called/assigned to the local before or after that whole section is parsed? (It is further down in the lua)

**Comment by Xaver-DaRed** [comment] 2023-04-25 00:06
I cannot reproduce this.
This happens in catseye aswell though, so if I had to guess... Teo, is your server divided into multiple processes?

The issue I'm thinking is that one server cannot get the proper GetRegionInfluence(zone:getRegionID()) value, so it defaults to null or 0, whatever, leading into that message.

The actual message IDs havent changed, so the issue is, definately, the "influence" value getting lost/not fetched correctly.

But as I said, I cannot reproduce it, so this is all a very wild guess.

**Comment by TeoTwawki** [comment] 2023-04-25 00:40
nope, one big happy instance for now. Also the tally seems to arrive a full earth day late and I've not touched the time offset values at all so that should be happening Sunday morning my time. I think we have an off by one error with that.

But initially I thought the region point storage was wonky (I did see some rows that didn't seem to add up to the expected total, which lead me to reset them to defaults). Its for sure fetching data as well. 

Thought possibly we're mingling messages for region influence trends (which tip you off what's happening NEXT tally) with current region control but neither line sup with what the map shows.

The maps region controls show something not even close to a 3 way deadlock. 

I forget the exact conditions for nations being allied but windy had a large lead, sandy in second, bastok in 3rd by a 2 region difference between it and sandy. Conquest map shows windy in 1st and sandy+bastok allied, messages say 3 nation deadlock and bastok+sandy allied but neither the region influence leading up nor the actual region controls should have that. 

It's as if there are extra regions in the count or missing from the count that don't exist in the map.

**Comment by claywar** [comment] 2023-05-25 19:16
@TeoTwawki Are you still seeing this? I had a first + two-way for second and third the other day on my test instance

**Comment by TeoTwawki** [comment] 2023-05-25 19:29
yes, the new testbed I set up seems to be having to it as well. The testbeds a fresh database.

**Comment by WinterSolstice8** [comment] 2023-05-28 06:19
This issue was just messaging in a city. A city is owned by no-one (255), not 0-3, so it always appears to be a deadlock as it has no data from a database query on who owns it. Retail does not send this conquest message in cities -- only global influence (i.e. who's first, second, third, tied, allied)

**Closed as completed** 2023-05-29 08:17 UTC
Labels: bug
