### ISSUE TITLE
🐛 Server fails to compile on Arch Linux with Clang 18 (-Wnan-infinity-disabled)

### ISSUE THREAD

**Issue by jefferyrlc** [DerpyProjectGroup/topaz#6060] opened 2024-07-30 23:05 UTC
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)

Arch Linux
## Branch affected by issue 

`base`

## Steps to reproduce

git clone --recursive https://github.com/LandSandBoat/server.git
cd server
python3 -m venv venv
CFLAGS="-Wno-error=incompatible-pointer-types"  venv/bin/pip3 install -r tools/requirements.txt
cp settings/default/* settings
mkdir build
cd build
cmake -DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_CXX_COMPILER=/usr/bin/clang++ ..
make

## Expected behavior

server to build with clang

terminal outputs this error:
build/_deps/fmt-src/include/fmt/format.h:2769:10: error: use of infinity is undefined behavior due to the currently enabled floating-point options [-Werror,-Wnan-infinity-disabled]

on further note, it does seem to compile with gcc I prefer clang as it's normally a faster compile than gcc

**Comment by zach2good** [comment] 2024-08-09 11:54
After some googling:
https://github.com/cms-sw/cmssw/issues/45181

and looking at where it claims the problem is:
https://github.com/fmtlib/fmt/blob/master/include/fmt/format.h#L2630-L2641

I reckon you can probably get around this by disabling fast-math, add this to your CMake configuration: `-DENABLE_FAST_MATH=OFF`
https://github.com/LandSandBoat/server/blob/base/cmake/StandardProjectSettings.cmake#L36

Which is the only option we manually set relating to floating point math.

What versions of clang and gcc are you using? Useful for us to know how far ahead you are (we'll always pin to whatever the latest versions are used by the latest Ubuntu LTS provided by GitHub action runners).

**Comment by zach2good** [comment] 2024-08-09 11:54
Don't worry about performance, the margins for `fast-math` are negligible, even at Horizon server-scale: https://github.com/LandSandBoat/server/wiki/Does-ffast-math-flag-matter

**Comment by jefferyrlc** [comment] 2024-08-09 22:59
gcc - 14.1.1+r309+gbb34b7eda1f-1
clang - 18.1.8-2

And let me retry with that flag and get back with you.

**Comment by jefferyrlc** [comment] 2024-08-09 23:10
Still no good
[error.log](https://github.com/user-attachments/files/16567592/error.log)

**Comment by zach2good** [comment] 2024-08-10 08:43
Arch is on our "experimental" list, and it's an advanced/bring-your-own-batteries distro anyway - so unless it's as simple as changing a single flag (which we've just looked at), we're probably not going to pay this any additional mind, especially if you can get a build going with GCC.

I'll have a little play with docker and see if I can repro this with `clang-18` on whatever Ubuntu release will give me `clang-18`, but ultimately this is out of scope for us, as we pin to `clang-15` in our CI.

I'll report back if I have good news.

**Closed as not planned by zach2good** 2024-08-10 08:43 UTC
Labels: bug

**Comment by zach2good** [comment] 2024-08-10 11:39
I couldn't repro using docker, but I could repro the combo of fastmath, this flag, and fmt in godbolt: https://www.godbolt.org/z/ss6WjxMb9

You can try adding `-Wno-nan-infinity-disabled` to clang section in `CompilerWarnings.cmake`, we have some exceptions in there for other external libs - should work

**Comment by jefferyrlc** [comment] 2024-08-10 15:38
I know you closed this as not planned, but adding that flag to CompilerWarnings.cmake worked. The server built fine with clang; so maybe adding that officially going forward should be the way to go.

**Comment by zach2good** [comment] 2024-08-11 09:47
We can't add this exception flag, since it only comes in in clang-18. Trying to add it will result in a warning of "unknown flag". It's not reasonable for us to have logic to say "if clang version is 18 or more, add flag" for a version that is 3 versions in the future of what we currently use.
